kubeProxyReplacement: true 
gatewayAPI.enabled: true

l2announcements:
  enabled: true

externalIPs:
  enabled: true

operator:
  replicas: 1  # Uncomment this if you only have one node
  rollOutPods: true
